import {CANDLE_UPDATE, CONN_CLOSE, CONN_CONNECTING, CONN_OPEN, START_TRADING} from '../actions/websocket';

export const messageTypes = [
  CONN_OPEN,
  CONN_CLOSE,
  CONN_CONNECTING,
  CANDLE_UPDATE,
  START_TRADING,
];